# -*- coding: utf-8 -*-
"""
vhbbtools
=========

This Python package provides classes and functions which ease the development
of CMS physics analyses using ntuples generated by the VHiggsBB Heppy framework.

:copyright: (c) 2017 by Sean-Jiun Wang.
:license: MIT, see LICENSE for more details.
"""


__version__ = '0.1.0.a2'

